### ISSUE TITLE
Consider publishing releases from GitHub Action workflow

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1570]
See also (ossf scorecard Packaging check)[https://github.com/ossf/scorecard/blob/main/docs/checks.md#packaging].

As noted in [this discussion](https://github.com/remkop/picocli/commit/87ff7a67bb0310e399823fb2b3950cc51b997990#commitcomment-65819656), the [openssf dashboard](https://metrics.openssf.org/grafana/d/default/metric-dashboard?orgId=1&var-PackageURL=pkg:github%2Fremkop%2Fpicocli) currently has no way to search Maven Central for published packages, so it only recognizes packages that are published from the GitHub workflow.

The workflow configuration below is a modified version of the publishing workflow I contributed to [petermr/ami3](https://github.com/petermr/ami3/blob/master/.github/workflows/create-release-and-publish-packages.yml).
It needs a bit more work to get the signing publications part to work.

```yaml
# This GitHub Action workflow is triggered by a git tag being pushed where the tag name starts with 'v'.
# The workflow runs two jobs:
# - create a GitHub Release from the git tag, using RELEASE-NOTES-NEXT.md as the release notes
# - build a package using Maven and then publish it to GitHub packages
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# (Alternatively, create the GitHub Release manually, which then triggers the `publish` job.)
#on:
#  release:
#    types: [created]

name: Create Release and Publish to GitHub Packages

jobs:
  build:
    # See https://github.com/actions/create-release
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: picocli ${{ github.ref }}
          body_path: RELEASE-NOTES-NEXT.md # generate during build
          #          body: |
          #            Changes in this Release
          #            - First Change
          #            - Second Change
          draft: false
          prerelease: false

  publish:
    # See: https://github.com/actions/setup-java#publishing-using-apache-maven
    # See: https://docs.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-maven#publishing-packages-to-github-packages
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      # TODO see https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Gradle
      - name: Configure JDK 1.8
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # v2
        with:
          distribution: 'zulu'
          java-version: 1.8
          cache: gradle

      - name: Publish to Maven Central
        run: gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          MAVEN_OSS_USER: ${{ secrets.MAVEN_OSS_USER }}
          MAVEN_OSS_PASSWORD: ${{ secrets.MAVEN_OSS_PASSWORD }}
      - name: Close the Sonatype info/picocli staging repo
        run: gradlew closeAndReleaseRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          MAVEN_OSS_USER: ${{ secrets.MAVEN_OSS_USER }}
          MAVEN_OSS_PASSWORD: ${{ secrets.MAVEN_OSS_PASSWORD }}
```
