### ISSUE TITLE
Add JDKs to Travis CI build

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#610]
For example:

```
jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea
```

https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks
https://sormuras.github.io/blog/2018-05-31-jdk-matrix.html
https://www.deps.co/guides/travis-ci-latest-java/

**Comment by remkop** [comment]
On Trusty, this works:

```
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk: openjdk6
```
https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks
